name: Auto Retro (optional)
on:
  push:
    paths: [ '20_PROJECTS/**/3_Deliverables/**' ]
  workflow_dispatch:
jobs:
  retro:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          python3 scripts/retro_trigger.py
          if git status --porcelain | grep -q .; then
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m 'chore(auto): add Retro after deliverables update'
            git push
          else
            echo 'No changes to commit.'
