name: Stage Gate Validator
on:
  push:
    paths: [ '20_PROJECTS/**' ]
  pull_request:
    paths: [ '20_PROJECTS/**' ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python3 scripts/stage_gate_validator.py
